# Generated by Django 5.1.5 on 2025-05-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('donor', 'Donor'), ('ngo', 'NGO')], default='donor', max_length=10),
        ),
    ]
